### ISSUE TITLE
[ui-material-bottom-navigation] MDTabStrip background-color works on Android, but not on iOS

### ISSUE THREAD

**Issue by Ed-Simmons** [nativescript-community/ui-material-components#337]
- "@nativescript/core": "~8.1.1"
- "@nativescript/android": "~8.1.1"
- "@nativescript/ios": "~8.1.0"
- "@nativescript-community/ui-material-bottom-navigation": "^6.2.0",

I'm using the root `app.scss` to set styles globally, but the `background-color` property is only being applied on Android, iOS seems to be defaulting to `white`:

```scss
MDTabStrip {
  background-color: red;
  color: $gray;
  selected-item-color: $primary;
  un-selected-item-color: $gray;
}
```

![image](https://user-images.githubusercontent.com/70568004/138726045-877426a3-017b-4283-bcca-0492fb77b1c7.png)
