### ISSUE TITLE
[cardview] Android: ListView itemTap does not fire

### ISSUE THREAD

**Issue by manijak** [nativescript-community/ui-material-components#388]
When using the `CardView` component inside a `ListView` template, the ListViews `itemTap` event never fires. If i add the `tap` event on the `CardView` instead, the event fires, but the ripple-effect is gone. 

Issue only present on Android, works fine in iOS. 

```yaml
OS: macOS 12.2
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.15.0
npm: 8.5.5
nativescript: 8.2.3

# android
java: 11.0.15
ndk: Not Found
apis: 30, 31, 32
build_tools: 30.0.3, 32.0.0, 32.1.0
system_images: 
  - android-32 | Google APIs ARM 64 v8a
  - android-32 | Google Play ARM 64 v8a

# ios
xcode: 13.4.1/13F100
cocoapods: 1.11.3
python: 2.7.18
python3: 3.8.9
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 15.5
  - macOS 12.3
```

### Dependencies

```json
"dependencies": {
  "@nativescript-community/ui-material-cardview": "^7.0.18",
  "@nativescript/core": "~8.2.4",
  "@nativescript/theme": "^3.0.2",
...
},
"devDependencies": {
  "@nativescript/android": "8.2.3",
  "@nativescript/ios": "~8.2.3",
  "@nativescript/types": "~8.2.0",
  "@nativescript/webpack": "5.0.6",
..
}
```
