### ISSUE TITLE
MDTextField Android error with secure option

### ISSUE THREAD

**Issue by vallemar** [nativescript-community/ui-material-components#455]
With the next version of the core when we use the MDTextField component with the `secure` option I have this error.
This does not happen with the TextField component of N

```
  System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method onCreateView failed
  System.err: TypeError: nativeView.getTransformationMethod is not a function
  System.err:
  System.err: StackTrace:
  System.err: setSecureAndKeyboardType(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/text-field/index.android.js:43:0)
  System.err:   at [secure:setNative](file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/text-field/index.android.js:103:0)
  System.err:   at [secure:setNative](file: src/webpack:/nativescript-reordering/node_modules/@nativescript-community/ui-material-textfield/textfield.android.js:168:28)
  System.err:   at applyAllNativeSetters(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/properties/index.js:1136:0)
  System.err:   at initNativeView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/properties/index.js:1079:0)
  System.err:   at onResumeNativeUpdates(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:891:22)
  System.err:   at _resumeNativeUpdates(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:352:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:306:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:108:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/index.android.js:316:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at callFunctionWithSuper(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:387:0)
  System.err:   at callLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at loadView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:308:0)
  System.err:   at eachChildView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
  System.err:   at eachChild(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:811:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:307:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:108:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/index.android.js:316:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at callFunctionWithSuper(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:387:0)
  System.err:   at callLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at loadView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:308:0)
  System.err:   at eachChildView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
  System.err:   at eachChild(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:811:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:307:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:108:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/index.android.js:316:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at callFunctionWithSuper(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:387:0)
  System.err:   at callLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at loadView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:308:0)
  System.err:   at eachChildView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/layouts/layout-base-common.js:101:0)
  System.err:   at eachChild(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:811:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:307:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:108:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/index.android.js:316:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at callFunctionWithSuper(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:387:0)
  System.err:   at callLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at loadView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:308:0)
  System.err:   at eachChildView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/content-view/index.js:65:0)
  System.err:   at eachChildView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/page/page-common.js:112:0)
  System.err:   at eachChild(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:811:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:307:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/view-common.js:108:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view/index.android.js:316:0)
  System.err:   at onLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/page/index.android.js:38:0)
  System.err:   at (file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at callFunctionWithSuper(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:387:0)
  System.err:   at callLoaded(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:393:0)
  System.err:   at loadView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:560:0)
  System.err:   at _addViewCore(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:551:0)
  System.err:   at _addView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/core/view-base/index.js:536:0)
  System.err:   at onCreateView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/frame/index.android.js:764:0)
  System.err:   at onCreateView(file: src/webpack:/nativescript-reordering/node_modules/@nativescript/core/ui/frame/fragment.android.js:28:0)
  System.err:   at com.tns.Runtime.callJSMethodNative(Native Method)
  System.err:   at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1301)
  System.err:   at com.tns.Runtime.callJSMethodImpl(Runtime.java:1187)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1174)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1152)
  System.err:   at com.tns.Runtime.callJSMethod(Runtime.java:1148)
  System.err:   at com.tns.FragmentClass.onCreateView(FragmentClass.java:55)
  System.err:   at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
  System.err:   at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
  System.err:   at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
  System.err:   at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
  System.err:   at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
  System.err:   at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
  System.err:   at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:547)
  System.err:   at android.os.Handler.handleCallback(Handler.java:942)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:99)
  System.err:   at android.os.Looper.loopOnce(Looper.java:201)
  System.err:   at android.os.Looper.loop(Looper.java:288)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:7872)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
```

my code
```
  <MDTextField :variant="variant" @textChange="onTextChange" @loaded="loaded" :text="text" :hint="hint"
    :secure="secure" />
```
