### ISSUE TITLE
[Switch]Throw exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by cloudhx** [nativescript-community/ui-material-components#477]
When adding the Switch component to the app, it throws the below exception.
I added the latest version like this `<MDSwitch v-model="value"></MDSwitch>` by following the guide, when replacing it with `MDButton`, it works.

Can anyone shed some light on it? Thank you so much!

```
 System.err: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
  System.err:
  System.err: StackTrace:
  System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
  System.err:   at android.text.StaticLayout.<init>(StaticLayout.java:460)
  System.err:   at androidx.appcompat.widget.SwitchCompat.makeLayout(SwitchCompat.java:995)
  System.err:   at androidx.appcompat.widget.SwitchCompat.onMeasure(SwitchCompat.java:916)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.StackLayout.onMeasure(StackLayout.java:89)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.FlexboxLayout.measureHorizontal(FlexboxLayout.java:613)
  System.err:   at org.nativescript.widgets.FlexboxLayout.onMeasure(FlexboxLayout.java:387)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureChildFixedColumns(GridLayout.java:1026)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureFixedColumnsNoStarRows(GridLayout.java:825)
  System.err:   at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:917)
  System.err:   at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:351)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
  System.err:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  System.err:   at androidx.cardview.widget.CardView.onMeasure(CardView.java:260)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureChildFixedColumns(GridLayout.java:1026)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureFixedColumnsNoStarRows(GridLayout.java:825)
  System.err:   at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:917)
  System.err:   at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:351)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1126)
  System.err:   at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:936)
  System.err:   at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:351)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1126)
  System.err:   at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:936)
  System.err:   at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:351)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:39)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
  System.err:   at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1126)
  System.err:   at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:936)
  System.err:   at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:351)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
  System.err:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  System.err:   at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
  System.err:   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
  System.err:   at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
  System.err:   at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
  System.err:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
  System.err:   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
  System.err:   at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
  System.err:   at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7951)
  System.err:   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
  System.err:   at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1173)
  System.err:   at android.view.View.measure(View.java:27131)
  System.err:   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4187)
  System.err:   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2936)
  System.err:   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3204)
  System.err:   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2618)
  System.err:   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9971)
  System.err:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
  System.err:   at android.view.Choreographer.doCallbacks(Choreographer.java:809)
  System.err:   at android.view.Choreographer.doFrame(Choreographer.java:744)
  System.err:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
  System.err:   at android.os.Handler.handleCallback(Handler.java:938)
  System.err:   at android.os.Handler.dispatchMessage(Handler.java:99)
  System.err:   at android.os.Looper.loop(Looper.java:246)
  System.err:   at android.app.ActivityThread.main(ActivityThread.java:8625)
  System.err:   at java.lang.reflect.Method.invoke(Native Method)
  System.err:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
  System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
